### ISSUE TITLE
Saving Preset

### ISSUE THREAD

**Issue by shift838** [ramapcsx2/gbs-control#100]
I have downloaded and loaded the newest 'gbscontrol' software.  I want to save my preset but when I click on a preset slot, any slot (1-9) I get the below error:

saveUserPrefs: open file failed

Of course trying to click Save Custom Preset anyway then I get:

Please select a preset slot first!

**Comment by Nuck-TH** [comment]
Did you set SPIFS(Flash size) to 1M?

**Comment by ramapcsx2** [comment]
See here:
https://github.com/ramapcsx2/gbs-control/wiki/Software-Setup#esp8266-ide-settings

**Comment by shift838** [comment]
DOH.  I selected No SPIFFS that will do it.
