### ISSUE TITLE
Wierd screen issue

### ISSUE THREAD

**Issue by wally86** [ramapcsx2/gbs-control#107]
I have gbs control up and running fine. I'm using a S-Video to Component transcoder (Koryuu). It just converts the signal, no scaling or lag. I'm getting wierd screen issue. The picture flashes in and out and has a tearing like effect. I've tried a few option with no improvements. Any help would be appreciated. Thanks

![IMG_20200326_214518](https://user-images.githubusercontent.com/8765045/77799840-02802780-704c-11ea-8f40-44a202ca5539.jpg)

[Video of problem. If it will help.](https://youtu.be/n658pFzE0Ug)

**Comment by wally86** [comment]
https://i.imgur.com/rXebxPR.jpg

**Comment by ramapcsx2** [comment]
Hey,
you need to give a little more detail. What is the format that goes into the GBS, and what kind of cabling do you use?

**Comment by wally86** [comment]
N64 via S-Video which is being transcoder to Component video. I'm using cables component to the component in on the gbs 8200.

**Comment by wally86** [comment]
I was talking to amoore2600. He told me that it's probably the Sync on Green capacitors that are causing the video to go crazy. Can you confirm this? If so will these here work?

https://rover.ebay.com/rover/0/0/0?mpre=https%3A%2F%2Fwww.ebay.com%2Fulk%2Fitm%2F163399061673

**Comment by ramapcsx2** [comment]
Yes, they'll make sync separation easier, but this shouldn't be required.
Any other Component source works just fine, so yeah..

**Comment by tvirusx** [comment]
Hi, there... while we are talking sync. does the GBS8200 have any issues with CSYNC signal???? I have a snes mini and I installed that Voultar board to restore RGB and when I pull sync through LUMA e work beautifully but from CSYNC there is some instabilities on the signal some flickering.. so am just using LUMA, but on Genesis that I have to get the signal from sync on composite, so the signal has a lot of interference. any thoughts??? I replaced the R34 resister like the wiki and c33 and c35.

The funny part is that I recently bought the Retrotink Scart 2x and it does not accept CSYNC, only LUMA or sync on composite according to Mike, but the image on the GBS at 1080p is way WAY crisper and better on my opinion. Great job to you guys on this project.

**Comment by wally86** [comment]
> Yes, they'll make sync separation easier, but this shouldn't be required.
> Any other Component source works just fine, so yeah..

This is the transcoder I have. Im new to the whole sync/csync stuff. I don't have the means to having my n64 RGB modded, so S-Video is my only option.

**Comment by tvirusx** [comment]
Did

> 
> 
> > Yes, they'll make sync separation easier, but this shouldn't be required.
> > Any other Component source works just fine, so yeah..
> 
> https://videogameperfection.com/products/koryuu-transcoder/
> 
> This is the transcoder I have. Im new to the whole sync/csync stuff. I don't have the means to having my n64 RGB modded, so S-Video is my only option.

Did u try composite from N64 to Koryuu and then to the GBS???? did u go to the WEB interface and try diferente resolution????

**Comment by wally86** [comment]
I did try composite. Same issue. I have tried every resolution in the control panel. Still the same. :(

**Comment by ramapcsx2** [comment]
CSync is the pure form of the same signal that it embedded in Luma (Luma is black and white video + CSync) and also Composite Video (black and white + color + CSync).
So the logic is the same, but the voltage level and stability differs.

If CSync from a modded SNES Mini doesn't work, then I'd start checking the cable.
The cable should have the components (maybe a resistor, maybe none) on the Sync line that the mod requires.
Voultar usually specifies what the cable should have.

**Comment by ramapcsx2** [comment]
Extra note: This applies only to SCART / VGA type connections, not the Component input.
The Component input should just work, no modifications required (unless the source does something funny, or the GBS board has a defect, or the cable is bad).

**Comment by wally86** [comment]
Not sure if this helps at all. But I have ran my transcoder into the component on the gbs without the esp8266 and it outputs the picture fine. (Well as fine as the stock board can do)

**Comment by ramapcsx2** [comment]
This suggests a timing problem that I haven't encountered yet.
I developed gbscontrol using home consoles. All consoles that have a Component option have been tested and work, from 240p to 1080p.

If you have access to logs, please paste a few lines here. Maybe I can see something (but probably not).

**Comment by wally86** [comment]
Since I'm having trouble with the component in. Could I use this Scart to VGA adapter, then add the S-Video to Scart adapter to that so I can use my n64 via S-Video?

![50123ff](https://user-images.githubusercontent.com/8765045/78185206-b4e33080-7438-11ea-8512-34beb9a1e36e.jpg)
![EHdAe_CUwAAXr9j](https://user-images.githubusercontent.com/8765045/78185232-bc0a3e80-7438-11ea-89af-9ecff62eb758.jpeg)

**Comment by wally86** [comment]
What does it mean when the esp8266 keeps blinking blue and the picture is scrambled?

**Comment by wally86** [comment]
*h: 428 v: 475 PLL:0 A:7b7b7b S:07.10.00 H-   I:40 D:058c m:0 ht:3566 vt: 273 hpw: 264 u: 21 s: 0 S:14 W:31
h: 428 v: 475 PLL:0 A:7b7b7b S:07.10.00 H-   I:40 D:058c m:0 ht:3567 vt: 273 hpw: 264 u: 22 s: 0 S:14 W:31
h: 428 v: 475 PLL:1 A:7b7b7b S:07.10.00 H-   I:40 D:058c m:0 ht:3565 vt: 266 hpw: 263 u: 28 s: 0 S:14 W:31
h: 428 v: 475 PLL:1 A:7b7b7b S:07.10.00 H-   I:40 D:058c m:0 ht:3566 vt: 266 hpw: 264 u: 29 s: 0 S:14 W:31
h: 428 v: 475 PLL:0 A:7b7b7b S:07.10.00 H-   I:40 D:058c m:0 ht:3565 vt: 266 hpw: 130 u: 2a s: 0 S:14 W:31
h: 428 v: 475 PLL:0 A:7b7b7b S:07.10.00 H-   I:40 D:058c m:0 ht:3565 vt: 266 hpw: 264 u: 2b s: 0 S:14 W:31
h: 428 v: 475 PLL:0 A:7b7b7b S:07.10.00 H-   I:40 D:058c m:0 ht:3565 vt: 266 hpw: 264 u: 2c s: 0 S:14 W:31
h: 428 v: 475 PLL:0 A:7b7b7b S:07.10.00 H-   I:40 D:0508 m:0 ht:3566 vt: 266 hpw: 263 u: 2d s: 0 S:14 W:31
h: 428 v: 475 PLL:0 A:7b7b7b S:07.10.00 H-   I:40 D:058c m:0 ht:3565 vt: 266 hpw: 130 u: 2e s: 0 S:14 W:31
h: 511 v: 475 PLL:0 A:7b7b7b S:07.10.00 H-   I:40 D:058c m:0 ht:3565 vt: 278 hpw: 263 u: 2f s: 0 S:14

**Comment by wally86** [comment]
That is with my Koryuu running N64 via S-Video to Component on gbs

**Comment by wally86** [comment]
(WiFi): AP mode (SSID: gbscontrol, pass 'qqqqqqqq'): Access 'gbscontrol.local' in your browser
<reset>
Chip ID: 1A 1
<reset>
Activity detected, input: Component

2345678
Format change: 1 <stable>
ADC offset: R:46 G:44 B:45

preset applied: 720x480 for NTSC 60Hz 


.* (debug) ign. length: 0x4E

.* (debug) ign. length: 0x4C

.* (debug) ign. length: 0x4C
.* (debug) ign. length: 0x4E
..* (debug) ign. length: 0x53
 (debug) ign. length: 0x63

.* (debug) ign. length: 0x4C

.* (debug) ign. length: 0x4E

.* (debug) ign. length: 0x4E

.* (debug) ign. length: 0x50

..* (debug) ign. length: 0x4E

**Comment by ramapcsx2** [comment]
It is a software problem with the sync signal that the Koryuu produces. This is what I can tell from the log.
I would need access to your setup to fix it, or at least a Koryuu unit here.

I wonder what's so different with the signal, over all the other sources that I've tested so far..

Anyway, you may have some success swapping the SOG capacitor for the Component input.   
The software is marginal / almost working, so the capacitor change might push it over the threshold.  
https://github.com/ramapcsx2/gbs-control/wiki/Sync-on-Green-Capacitor-Replacements

**Comment by ramapcsx2** [comment]
Ah, one more suggestions:
Since this is the Component input, I may not be very aggressive adjusting an important sync separation parameter on it.
You can try accessing the web interface, go to the developer tab, and hit the "SOG Level--" button a few times.
This may or may not work better with "Disable Syncwatcher", which is on the same tab.
You can also enable info prints there, and watch them while tweaking these settings.
You know it gets better when the readouts become more even looking (and the picture gets better :p).

**Comment by wally86** [comment]
syncwatcher off
Phase: 12 SOG: 11
Phase: 12 SOG: 10
Phase: 12 SOG: 9
Phase: 12 SOG: 8
Phase: 12 SOG: 7
Phase: 12 SOG: 6
Phase: 12 SOG: 5
syncwatcher on
 (debug) ign. length: 0x4D

..* (debug) ign. length: 0x4D

. (debug) ign. length: 0x62
.*Phase: 12 SOG: 4
 (debug) ign. length: 0x4D

.*Phase: 11 SOG: 3
 (debug) ign. length: 0x4D

.*Phase: 12 SOG: 2
 (debug) ign. length: 0x4B

.* (debug) ign. length: 0x4D

. (debug) ign. length: 0x62
.* (debug) ign. length: 0x4B
 (debug) ign. length: 0x62

.* (debug) ign. length: 0x4B

.Phase: 16 SOG: 1
* (debug) ign. length: 0x4B

.* (debug) ign. length: 0x4B

.Phase: 16 SOG: 1
* (debug) ign. length: 0x4D

.* (debug) ign. length: 0x4B

.* (debug) ign. length: 0x4B

.* (debug) ign. length: 0x4B
 (debug) ign. length: 0x62

.Phase: 16 SOG: 1
* (debug) ign. length: 0x4B

.Phase: 16 SOG: 1
* (debug) ign. length: 0x4D

.* (debug) ign. length: 0x4D

.* (debug) ign. length: 0x4D

.* (debug) ign. length: 0x4B

.*syncwatcher off
Phase: 16 SOG: 1
Phase: 16 SOG: 0

**Comment by wally86** [comment]
I pushed the sog level button until it won't go any lower, no difference. When I push syncwatch button picture wasn't flickering in and out anymore, but shaking and scrambled.

**Comment by ramapcsx2** [comment]
Okay, then it's not the sync level / amplitude, but the sync pulse width or the way VSync is embedded.
It's a problem where I really need to have access to the problem device.

**Comment by wally86** [comment]
Ok. I got ya. Here is a picture for the 1 second the picture locks in. Looks soooo good. Hope someone can help figure it out.
![IMG_20200401_203840](https://user-images.githubusercontent.com/8765045/78278547-33e17300-74e4-11ea-8617-de165fc6ed8d.jpg)

**Comment by wally86** [comment]
I know it must be something with the Koryuu, because when I turn on the koryuu the test color lines do the same thing without a input plugged in

**Comment by wally86** [comment]
Would something like this work better than the koryuu? All the input and output info is in the link.

https://www.ebay.com/itm/Composite-S-Video-to-Component-YUV-RGB-RGsB-Sync-On-Green-Converter-/251001590643

**Comment by ramapcsx2** [comment]
Probably not, no. Generic converters usually don't work well with games. Expect forced deinterlacing and the likes.

I have asked people in the forums whether they have Koryuu units. Maybe one of them can help.

**Comment by wally86** [comment]
hopefully someone does. is there any other way to get s-video into the gbs with correct scaling, etc? I'm looking into replacing the capacitors, never done a capacitor before and they are mighty small.

**Comment by tomudo** [comment]
> 
> 
> is there any older version of the firmware i could test? maybe get something useful out of.

on https://github.com/ramapcsx2/gbs-control, click  "### commits" -> click whatever old version ->  click "browse file" -> click download

**Comment by wally86** [comment]
@tomudo thanks. 

I got something working, kind of...

I downloaded commit 106c4639c368140256b705dbd2308d512c3cfb8e picture was flickering only slightly. I was able to push syncwatch at just the right moment and lock in the picture and works with no problem.

**Comment by wally86** [comment]
![IMG_20200403_003423_90](https://user-images.githubusercontent.com/8765045/78325323-4c35aa00-7545-11ea-8b4f-38eace7c7300.jpg)

**Comment by ramapcsx2** [comment]
Yes sure, try and find an even older version still.
I added the variable sync window code to support a much wider range of sources, but it isn't perfect.
The more "dumb" (static) version I used before will either work all the time, or not at all.
Sometimes stuff goes like that.  
I need a Koryuu to fix the "smarter" version for it. It's obviously a kind of corner case that I don't consider right now, but I don't know which.

**Comment by wally86** [comment]
Well I wouldn't call the issue resolved. I don't know why I didn't think of doing it earlier. I wanted to use the gbs8200 for N64 and PS1, for games that have resolution changing during mid gameplay. Because my OSSC loses signal for 5-10 seconds every time the resolution changes. What I did was connect the Koryuu via component to the gbs8200 (stock) to component IN. Then connected the VGA  out on the gbs8200 to the VGA in on the OSSC. Then set the OSSC to passthru. Looks amazing. No signal lose. And scanlines and all the options of the OSSC.

**Comment by tvirusx** [comment]
> 
> 
> CSync is the pure form of the same signal that it embedded in Luma (Luma is black and white video + CSync) and also Composite Video (black and white + color + CSync).
> So the logic is the same, but the voltage level and stability differs.
> 
> If CSync from a modded SNES Mini doesn't work, then I'd start checking the cable.
> The cable should have the components (maybe a resistor, maybe none) on the Sync line that the mod requires.
> Voultar usually specifies what the cable should have.

Found my issue with CSync... I just mod my NES with the RGB board and it works fine via CSync. So that made me go back to basic and recheck everything and the CSync wire was in the wrong hole. Solder it to the proper hole and WOW it works...

**Comment by wally86** [comment]
Do scanlines still work with 480i?

**Comment by wally86** [comment]
Decided to get a Retrotink 2x to run into gbs control board. No issues.
