### ISSUE TITLE
Scanline options for 480p?

### ISSUE THREAD

**Issue by wally86** [ramapcsx2/gbs-control#110]
Do scanline options work for 480p input on gbs 8200 via VGA input?

I'm trying my S-Video to VGA line doubler into the VGA IN on the gbs 8200. I'm using a vga cable plugged into the VGA port on the gbs 8200. Signal is 480p.

**Comment by ramapcsx2** [comment]
No, unfortunately that doesn't work.
The hack that produces the scanlines only works with 240p sources.
