### ISSUE TITLE
[Feature request] Auto switching Bob/Motion by progressive scan detection.

### ISSUE THREAD

**Issue by tomudo** [ramapcsx2/gbs-control#121]
I read description in preference of gbscontrol web UI.

```
Gbscontrol detects interlaced content and automatically toggles deinterlacing.
- Bob Method: essentially no deinterlacing, no added lag but flickers
- Motion Adaptive: removes flicker, adds 1 frame of lag and shows some artefacts in moving details
If possible, configure the source for progressive output. Otherwise, using Motion Adaptive is recommended.
```
From description above, I understand that "bob" is best for progressive and "motion adaptive" should be used in interlaced, right? 

I use gbs control for PS2 game which each games use different interlace / progressive mode. Could you add auto switching bob/motion by interlaced/progressive detection?

**Comment by Nuck-TH** [comment]
It is both methods of deinterlacing. If input is progressive it is processed as is.

**Comment by tomudo** [comment]
Ok. I got it.
