### ISSUE TITLE
480i RGB transcoding (without scaling) to YPbPr

### ISSUE THREAD

**Issue by famiclone6502** [ramapcsx2/gbs-control#129]
No combination of settings seems to allow a pass-through of a 15kHz 480i RGB signal to YPbPr without enabling the scaler. It looks as if I connected a VGA cable to component without the GBS. 

I am using a stock HCKJ 8200 V5.1 with yellow buttons with ESP8266 NodeMCU CP2102 ESP-12E.

**Comment by ramapcsx2** [comment]
Right, the pass through option does not process the source signals. The output will still be in the wrong format.
Transcoding needs digital processing to convert the signals.

**Comment by famiclone6502** [comment]
Understood. Thanks!

**Comment by balazer** [comment]
My GBS-C converts 480p YPbPr component to RGBHV in pass through mode.  So maybe something changed.
