### ISSUE TITLE
Preset 720x480 on 4:3 crt pc monitor

### ISSUE THREAD

**Issue by Solidzera** [ramapcsx2/gbs-control#156]
Hi I am using the amazing GBS Control with a pc CRT monitor 4:3 LG 17" 710E with PS2 and Wii through component cable.
When I use 480p game on PS2 or Wii on 480p mode and use GBS Control on Passthrough mode the pc monitor use full horizontal width without black border on the right and left sides of the image.

But when I use 720x480 mode on GBS Control on 480i/240p games the pc monitor gets black border on the right and left sides and the horizontal width is set at max on the monitor already.

I tried to use scaling on GBS Control but I get geometry problem verified on 240p test suite.

I have noticed that older GBS Control version had 640x480 mode instead of 720x480.

There is a way to solve this? Thanks in advance for this amazing project!

**Comment by ramapcsx2** [comment]
Hey, this basically falls under adding another preset.
I don't want to do that anymore, since each preset multiplies maintenance effort.

But instead, please try the Picture Controls functions. Maybe you can find a good setting, then save it as a custom preset.

The behaviour of your monitor sounds a bit weird, by the way. The timings are correct to fill the entire width of the screen.

**Comment by Solidzera** [comment]
No problem Rama! 
I will do a new custom preset for it.

**Comment by Solidzera** [comment]
When I use passthrough on 480p input signals no problem at all. Only when I use 740x480 or 1280x960 preset i get black borders on the right and left sides.

No problem Rama! I am going to create a new preset for it with Picture Controls on GBS as you recommend. 
Continue with your great work!!

**Comment by gingerbeardman** [comment]
Is it possible to share the preset? I've been wanting this also.

**Comment by Solidzera** [comment]
@gingerbeardman I made a custom preset using Picture Controls
Is this you want?
![image](https://user-images.githubusercontent.com/73763126/98303144-67b1d900-1f9c-11eb-8b14-b4543f4b0d7b.png)

**Comment by Solidzera** [comment]
Also @ramapcsx2 I bought a board that came with a switch for select rgbhv or component circuit for output.
Is there a problem or it is safe using component output from this circuit for crt pc monitors?
I noted the image is even brighter over component than over rgbhv 
And is even better somehow

**Comment by gingerbeardman** [comment]
@Solidzera thanks! also can you share where you bought your board? thanks!

**Comment by Solidzera** [comment]
@gingerbeardman from this amazing people in Brazil:
https://gamescare.com.br/produto/gbs-control-gamescare-scaller-1080p/
I recommend their products!
