### ISSUE TITLE
Horizontal Green and purple lines cycle through image

### ISSUE THREAD

**Issue by Sinaloagold** [ramapcsx2/gbs-control#157]
I just installed the GBS control firmware along with a clock Gen mod and the I get these Horizontal Green and purple lines scrolling  through image.

https://youtu.be/f1jesK_0qmc

Would this have to do with LDO cap? Thanks.

**Comment by ramapcsx2** [comment]
I'm sorry, i can't see them ><

**Comment by Sinaloagold** [comment]
I forgot to update, it's hard to see them through video, but what fixed it was swapping  to a better power supply and cable. Thanks
