### ISSUE TITLE
WiFi reset and connection assertion

### ISSUE THREAD

**Issue by chipnetics** [ramapcsx2/gbs-control#166]
Thanks for the brilliant project.... two issues I've discovered:

In regards to the menu item "System->Connect to Wifi Network";

1. If you put in a non-existent SSID or wrong password, there is no assertion feedback; it applies the settings, restarts, and you are hooped to access the device without doing a re-flash in the Arduino IDE (if you entered the wrong information).

Also, for properly connected devices to the users local WiFi, performing "System->Reset Defaults+Restart" does not reset the WiFi configuration and give you access to the "gbscontrol" access point again.  This is an issue if people switch routers in the future or move locations to a different SSID in the home.  They either have to do a reflash, or perform the  "Connect to Wifi Network" process again with both SSIDs accessible, and running, such that they can still be able to access the device and input the information for the new SSID.

**Comment by ramapcsx2** [comment]
Yea, these were all limitations of the SDK and libraries back when I added it.
It might be better these days, but I don't expect there to be, for example, a robust system in place that can:
- try to connect to a hotspot / router
- on failure, revert to the old settings

This may be asking a bit much of the microcontroller.
