### ISSUE TITLE
Wrong colors On Amiga

### ISSUE THREAD

**Issue by Foul** [ramapcsx2/gbs-control#181]
I made all the hack proposed but the colors are weird.. here is a screen : https://img.super-h.fr/image/q3V05

Original one : https://images.app.goo.gl/uQQR2qRfkoJBo7566

Real colors must be purple for background..  and blue for the floppy ,with my eyes I see brown color background and green floppy instead.

It seems blue is missing.. ( I checked 2 times wires on removed potentiometers..)

My Amiga is connected to the 8pin RGBS input.

**Comment by lovrenco** [comment]
Not software issue. Check your wiring. 
I built unit several days ago and colors are OK on A500 and A1200.
Bigger issue is that DblPAL resolution from the Amiga does not work correctly, and you cannot have 800x600 or 1024x768 output resolution in software.

**Comment by ramapcsx2** [comment]
More output presets increase development workload 10 fold. I don't have any time as it is :p 

As for the colors, that is clearly a swapped color line, as @lovrenco says.
Swap blue and green, I think.

**Comment by Foul** [comment]
after some research.. something wrong with blue RGB.. when i link Ground and red :working ground/green working... ground/blue :nothing .. nothing is moving with or wihout stripe on the Blue potentiometers (sorry for my language)

**Comment by lovrenco** [comment]
@Foul I am using just one ground (video ground from RGB23). Basically I reused Commodore video cable, 9pin.
This is connector on monitor side:
https://imgur.com/yoUSfYJ
So only pin 1 ground is used, R,G,B lines and pin3 CSync (with 680 ohm resistor). 
I built cable for GBS board with female DB9 connector, attached it and it works.

**Comment by Foul** [comment]
The Cable is not a problem, i use the same (own made) cable since many years and all was working before moding the GBS.

mine : https://img.super-h.fr/images/279f0eb4c88c2bdd8bf7b64c64f21706.jpg

**Comment by Foul** [comment]
Does anyone know where the blue line from the 8 pin connect is going? what pin does this line go to? I need to bridge this line.

**Comment by Foul** [comment]
a good weld and it's settled!
