### ISSUE TITLE
Force PAL 50 to 60 Hz not working anymore

### ISSUE THREAD

**Issue by redhair23** [ramapcsx2/gbs-control#206]
The switch is not working but I get similar info in memo field as "Get video timings"

**Comment by nightgryphon** [comment]
Same issue here. Has to rollback to previous version.

The possible reason is "PAL 50 to 60 Hz" command code is character "0" (zero) which can be false recognized as number 0 = false within new javascript code.

**Comment by Metacrack** [comment]
Same issue for me. Previous version works perfectly.

**Comment by gingerbeardman** [comment]
🚨 @xperiments
