### ISSUE TITLE
Question: Is it possible to adjust brightness and contrast and colors from the web UI?

### ISSUE THREAD

**Issue by lovrenco** [ramapcsx2/gbs-control#207]
When I look picture from Amiga 1200 on VGA 17' monitor using GBS scaler with gbs-control, colors are "washed" comparing to same machine outputting to PAL monitor, or PAL TV using SCART. 

I tried tuning that on monitor itself with some success but I wonder is there a way to tune image  brightness and contrast and colors form the scaler itself?

Thank you.

**Comment by gingerbeardman** [comment]
What is the status of the RGB pots on your GBS?

Have you tried Gain+/- or Auto Gain Adjust?

**Comment by lovrenco** [comment]
Gain+/- does the trick. But more control would be better, if something like that is even possible. 

> What is the status of the RGB pots on your GBS?
> 
> Have you tried Gain+/- or Auto Gain Adjust?

**Comment by gingerbeardman** [comment]
Did you adjust or remove the RGB potentiometers on your GBS PCB?

**Comment by lovrenco** [comment]
> Did you adjust or remove the RGB potentiometers on your GBS PCB?

I removed them.

**Comment by gingerbeardman** [comment]
Was that your solution?
