### ISSUE TITLE
How to revert to default chip to try 1024*768 resolution?

### ISSUE THREAD

**Issue by lovrenco** [ramapcsx2/gbs-control#215]
Hello, 
Is there a way to revert to default GBS8200 firmware without desoldering ESP8266 and clock generator?
I would like to see if small 14 inch CRT will work with 1024x768 resolution. 
Check photos. In 720x480 picture is crisp and stable, but there is no way to get it to show on full screen, not with monitor hardware, nor with ESP software controls. 1280x1024 is too much for this monitor (as is for any 15 inch display).

I tried removing jumper, no luck. Is there a way I can try default firmware without removing all components?

![1280x1024](https://user-images.githubusercontent.com/5626489/114597419-0d2a5080-9c91-11eb-9134-45a12de53db1.jpg)

![720x480](https://user-images.githubusercontent.com/5626489/114597391-056aac00-9c91-11eb-8d36-0f111d5ec67d.jpg)

**Comment by ramapcsx2** [comment]
The jumper has to be opened, and the ESP SDA / SCL disconnected.

**Comment by lovrenco** [comment]
I tried opening jumper, disconnecting ESP power line, but I get just a black screen, no video.

**Comment by Nuck-TH** [comment]
You have to disconnect data lines too.

**Comment by mpalpha** [comment]
Use this. https://github.com/ramapcsx2/gbs-control/issues/178#issuecomment-3881946079
