### ISSUE TITLE
Development and Master Branches.

### ISSUE THREAD

**Issue by andreacampanella** [ramapcsx2/gbs-control#29]
I really like this project but I'm always worried to update my esp8266 because there are always a lot of changes and sometime things get broken.

Perhaps the project need a Development branch were new changes can be tested and experimented and when the code is in a good shape can be deployed to Master.

**Comment by ramapcsx2** [comment]
Yeah, that is a problem indeed.
I'll consider your suggestion.

**Comment by ramapcsx2** [comment]
Branch created, let's see how it works out :)
