### ISSUE TITLE
GBS board not responding

### ISSUE THREAD

**Issue by BuddiScotch** [ramapcsx2/gbs-control#291]
Hey All,

To start off, yes the SDA and SCL pins have been triple checked.
I've tried multiple power supplies.
I've tried reflowing the solder on the contact points.
I've restarted it and reset all defaults.
I've tried switching between access point and connecting to my own wifi to remote in.
I've tried different VGA to HDMI adapters.

I'm sure I'm missing a bunch of basic troubleshooting steps that I absolutely did but don't remember. You know the drill.

If you've made it this far I place my future in your hands.

So my GBS board keeps throwing me the error of "GBS board not responding!" whenever I try to select a resolution. All the resolution options are greyed out.

It does not display anything, and on my TV it has no signal. So its not receiving any signal from the GBS 

Something to keep in mind is that the GBS board did not have any issues *prior* to me soldering the clock generator to the board. Afterwards, it was was having these issues but for a short period of time it still worked. However now its completely dead.

The wifi board still pops on the blue light when I boot, however it does not come on after that.
That and the red power LED for the board works.

I believe that's everything.

Thanks Al

![20211101_202706](https://user-images.githubusercontent.com/47334989/140009084-e54dcf59-5dc5-4cf3-b94d-3386f08e0183.jpg)
![20211101_202638](https://user-images.githubusercontent.com/47334989/140009087-b4ba20cc-86b0-438c-9a48-38eb8202f13f.jpg)
l
![20211101_202628](https://user-images.githubusercontent.com/47334989/140009091-fcd6ab7c-778c-4176-b888-1c33ff6f64f5.jpg)
![20211101_202606](https://user-images.githubusercontent.com/47334989/140009095-c4fcd5cb-03e5-4f83-9f08-5641265b8fad.jpg)
.

**Comment by TABYDACAT** [comment]
Have you tried utilizing C41 as well just to troubleshoot the clock gen?

**Comment by israpps** [comment]
@BuddiScotch Hi

im having this issue after clockgen install.

how did you fix the issue?
