### ISSUE TITLE
GBS-C options greyed out

### ISSUE THREAD

**Issue by deanodley** [ramapcsx2/gbs-control#347]
Hi - I'm not sure how or when this issue started... When I flashed the ESP8266 initially all settings could be toggled, but now almost all are greyed-out. I have tried re-flashing the ESP using both "only sketch" and then "all flash contents" but the issue persists.

Some of the options will change when clicked, as indicated in the developer console, but the UI does not update. The one I actually want to disable "matched presets" does not toggle or change in the UI or developer window.

It doesn't seem to matter if a signal is present or not.

Any help would be appreciated. Thank You in advance.

![greyedOut](https://user-images.githubusercontent.com/16767320/179270917-42ec6026-db64-4f04-8f37-67a80c5307ac.jpg)
.

**Comment by kimbapslice** [comment]
> I found a solution which may be useful for someone else in the future. The described behavior happens when there is no preset selected. Selecting any saved preset, or the empty one, enables access to the settings again. There appears to be a quirk in the UI which allows this scenario to happen.

Thank you, your workaround was extremely helpful as I was running into the same issue as I built the gbs control and thought I wired things incorrectly.
