### ISSUE TITLE
Unable to get IIGS working coherently with latest GBSControl

### ISSUE THREAD

**Issue by Simon-Bitdiddle** [ramapcsx2/gbs-control#356]
I am using a IIGS into a GBS8200, the only physical mod I am using is a 100 ohm resistor across the sync and ground pins. I have ensured that I am using the latest (7/29/2022) version of the software.

With the configurations completely reset, I am getting the following entries and then the ESP8266 resets.

...
<reset>
Scanning inputs for sources ...
Activity detected, input: RGB
VSync: present
HSync: present
RGB/HV
RGB/HV < > SOG

<reset>
...

What information can I provide to help troubleshoot this?

**Comment by ramapcsx2** [comment]
The computer may output CSync + VSync. If so, try to not connect the VSync signal.

**Comment by Simon-Bitdiddle** [comment]
I was able to solve my sync problems by connecting the debug line.
