### ISSUE TITLE
Updated to the latest firmware and GBS Board not responding

### ISSUE THREAD

**Issue by war3zlod3r** [ramapcsx2/gbs-control#358]
I was running an older build from a year or two ago and decided to update software process seemed to go smooth and followed all the steps in the guide to compile and upload the software but no dice. I get GBS board not responding when trying to change resolutions and no video output. This was working a couple hours ago, please help!

**Comment by gixxerfool** [comment]
> I was running an older build from a year or two ago and decided to update software process seemed to go smooth and followed all the steps in the guide to compile and upload the software but no dice. I get GBS board not responding when trying to change resolutions and no video output. This was working a couple hours ago, please help!

I have this exact issue, did you end up finding the issue? Thanks
