### ISSUE TITLE
Blurry image with NTSC feedback clock preset (PS2)

### ISSUE THREAD

**Issue by goutsune** [ramapcsx2/gbs-control#38]
Hi, I'm still tinkering with GBS and my PS2 console. What bother's me is that I can't get clean pixel perfect with NTSC preset but can do so with PAL by adjusting PLL divier and phase. It kinda looks like there's 2'nd level moire on top of the image as if it samples not 640 pixels but perhaps 512, although I can't see that in preset itself.

**Comment by ramapcsx2** [comment]
I don't have a guaranteed to work formula to optimize this. Sometimes a preset just won't look good with a particular source.
One other factor you could try is the sampling stop offset on S1_26. Send "x" on the terminal to advance this by 1. Sometimes it's off by 1 or 2.
