### ISSUE TITLE
Help! Blank screen.

### ISSUE THREAD

**Issue by ZeFoxii** [ramapcsx2/gbs-control#411]
My gbs control isn't displaying through hdmi or vga, I'm also new to this and bought the tzt one from AliExpress. I looked and the jumpers are bridged from visual inspection. I'm not sure what to do to get normal composite to work!

**Comment by ramapcsx2** [comment]
"Yellow White Red", you mean a standard Composite Video cable, right?
This hardware supports RGB and Component, but there is no decoder in it that can deal with Composite (or S-Video).
You need an RGB cable.

**Comment by ramapcsx2** [comment]
As a quick test, you can plug the yellow cable into the green Component port.
If it works, you should get a bad looking black and white picture.

**Comment by ZeFoxii** [comment]
Here is the pasteboard link so you can see what I see

https://pasteboard.co/YgajHDJcOD6S.jpg

**Comment by ZeFoxii** [comment]
It says no signal but I have no the the vga and hdmi connected, and the av cables connected is there some setting I need to set that isn't clear or is it plug in and it should show up?

**Comment by ramapcsx2** [comment]
It seems to be unstable, so it won't work. Maybe a different console will work though. The green port with Composite video is a hack only. It's not meant to work like that :p

**Comment by ZeFoxii** [comment]
Like this correct?![image](https://user-images.githubusercontent.com/31014416/217918895-214b93ed-a111-4edc-97f8-df2014fee2dd.jpeg)

**Comment by ZeFoxii** [comment]
The blue light no longer shows anything f is plugged in

**Comment by ZeFoxii** [comment]
Question what does this mean?![image](https://user-images.githubusercontent.com/31014416/217919385-86732f54-6577-4b4d-9fdf-365ad26f9e37.jpeg)

**Comment by ZeFoxii** [comment]
I got something f but a bad quality was not what I see

**Comment by ZeFoxii** [comment]
Now that I know there is a chance money hasn't been wasted I'm gonna take the time to ask some other questions,


Like what is this and what does it do,I messed with it in my moment of panic.
![image](https://user-images.githubusercontent.com/31014416/217922105-cc908901-d8c1-4e93-9cfb-8012256824b4.jpeg)

And what is this I also messed with this in my moment of panic,

![image](https://user-images.githubusercontent.com/31014416/217922284-2bdb8880-8384-4966-ae16-b40891ed5f2b.jpeg)

**Comment by ramapcsx2** [comment]
This is entirely different hardware. It seems to be an addon board that has a Composite Decoder.
Please undo everything and plug your yellow cable back into the yellow port that your device has.

**Comment by ZeFoxii** [comment]
I have confirmed the board does work with a snes. All I wanted to do was test it to make sure it wasn't broken and I have successfully done so.

**Comment by ZeFoxii** [comment]
Apparently the n64 isn't rgb comparable

**Comment by ZeFoxii** [comment]
That knob I was turning earlier controls how red or green it is, I thought that was controlled via software, I have a question do you guys have a discord channel? That way if I have any other questions or concerns I can ask not on GitHub?

**Comment by ramapcsx2** [comment]
You may find some info on the big retro gaming server if you look around:
https://discord.gg/KghjV79z

The server has a role system, so you may have to adjust your roles.
