### ISSUE TITLE
lifted pin

### ISSUE THREAD

**Issue by Firas-Dhouibi** [ramapcsx2/gbs-control#423]
so here the story
a accidentally grabbed the wire that connects the clock generator and the pin 40 on the trueview5725 chip and i ended up with a lifter pin, i cant soldered it back cuz there is no copper left.
is there a solution or better get another board ?

**Comment by nyanpasu64** [comment]
I *think* (am not confident, I didn't design the hardware) that you need to connect the clock generator to the chip's pin 40, and the trace on the PCB is not important. Is the pin still attached to the chip? Is the *trace* or the *pin* broken with "no copper left"?

**Comment by Firas-Dhouibi** [comment]
> I _think_ (am not confident, I didn't design the hardware) that you need to connect the clock generator to the chip's pin 40, and the trace on the PCB is not important. Is the pin still attached to the chip? Is the _trace_ or the _pin_ broken with "no copper left"?

yes the pin still attached to the chip, the trace on the board is gone

**Comment by YoImLee** [comment]
Lifting pin 40 is not a problem. In fact, the wiki used to recommend lifting it. But since it doesn't connect to anything you don't have to. As long as the pin is still there you're fine.

**Comment by Firas-Dhouibi** [comment]
> Lifting pin 40 is not a problem. In fact, the wiki used to recommend lifting it. But since it doesn't connect to anything you don't have to. As long as the pin is still there you're fine.

alright, thanks dude
