### ISSUE TITLE
8220 board mods. What is the capacitor value?

### ISSUE THREAD

**Issue by drawingangnam** [ramapcsx2/gbs-control#433]
![20230309_213454 copy](https://user-images.githubusercontent.com/127495963/224292677-504216c6-ac5f-4f74-90e1-9c4714077d85.jpg)

8220 board modification reference photo didn't make sense to me, so I drew a schematic by hand.

Is the schematic in the photo above correct?

If so, what value should the CAPACITOR be?

Any advice would be appreciated.

**Comment by ramapcsx2** [comment]
Hey,
I picked a random ferrite I salvaged, and the caps look like some 220nF I had plenty of at the time.
Looking at my soldering work, it would be more important to completely bridge the 0 Ohm R59 resistor to ground.
Even a 0 Ohm resistor has a very small non-zero value.

**Comment by drawingangnam** [comment]
Thanks for the lightning advice.
Can I organize the schematic as shown in the photo above?
![20230309_213454 copy 2](https://user-images.githubusercontent.com/127495963/224316990-97ecd4c8-9cef-4ce7-87fa-e743fc26af4c.jpg)

**Comment by ramapcsx2** [comment]
You need to remove the R58 resistor, of course. But then yep.

**Comment by drawingangnam** [comment]
> You need to remove the R58 resistor, of course. But then yep. Edit: Ie, FB replaces R58.

Thanks a Lot!
