### ISSUE TITLE
how i know if the clock generator is working ?

### ISSUE THREAD

**Issue by Firas-Dhouibi** [ramapcsx2/gbs-control#441]
so i did install the clock generator to my gbs-c board, and in the wiki its saying "To test the clock generator is working, open the GBS Control web gui. Go to Preferences and scroll down to Activate FrameTime lock. Press on the FrameTime Lock button and the console will read "Active FrameTime Lock not necessary with external clock gen installed". and thats what i did but instead its saying "active frametime lock enabled, adjusting external clock gen fresuency".

![336348220_901552777632029_4016004997518325280_n](https://user-images.githubusercontent.com/92697870/225927060-fe773c8b-a033-4f3e-867d-f0e912294e2e.jpg)

**Comment by YoImLee** [comment]
The wiki is outdated, the message you are seeing is correct with recent versions of gbs control. It is better to leave frametime lock enabled even with the clockgen installed now. It should be working. :)

**Comment by Firas-Dhouibi** [comment]
> The wiki is outdated, the message you are seeing is correct with recent versions of gbs control. It is better to leave frametime lock enabled even with the clockgen installed now. It should be working. :)

alright, thanks man

**Comment by wadetm** [comment]
I'm seeing a option in the developer menu "List Options" under the last item "disable external clock generator = 1" would this indicate that my external clock gen is not working? Below is a output of my debug logs

*****************************************************************************

Active FrameTime Lock enabled, adjusting external clock gen frequency

preset applied: 1280x1024 for scaling RGB (CSync)
Note: scaling RGB is still in development

source Hz: 59.92226 new out: 59.92226 clock: 162127040 (+127040)
user command 5 at settings source 4, custom slot 65, status 2
FTL off
user command 5 at settings source 4, custom slot 65, status 2
FTL on
Active FrameTime Lock enabled, adjusting external clock gen frequency
user command e at settings source 4, custom slot 65, status 2
/slots.bin 2304
/preferencesv2.txt 19
preset preference = 4
frame time lock = 1
preset slot = 65
frame lock method = 1
auto gain = 0
scanlines = 0
component output = 0
deinterlacer mode = 1
line filter = 0
peaking = 1
preferScalingRgbhv = 1
6-tap = 1
pal force60 = 0
matched = 1
step response = 1
disable external clock generator = 1
*****************************************************************************

**Comment by YoImLee** [comment]
No, your clockgen should be working fine.

**Comment by amaiorano** [comment]
> 

Not op, but why is the output displaying `disable external clock generator = 1` if it's not disabled? Is this just a bug?

**Comment by Firas-Dhouibi** [comment]
idk either, its displaying **disable external clock generator = 1** as well.
im at the latest FW version, maybe its a bug
