### ISSUE TITLE
On Dark Screen white Artefacts

### ISSUE THREAD

**Issue by MFreudenthaler** [ramapcsx2/gbs-control#444]
I have white Artefacts on the Screen. Also if i Use VGA in and VGA out.
Board is from 20220510 v4.0,
![24-03-_2023_07-48-31](https://user-images.githubusercontent.com/59617641/227446313-043f753e-602e-476d-a7a6-afe6fddd745e.png)

**Comment by nyanpasu64** [comment]
What input and output resolution are you using, and did you mess with image scale? Do the artifacts appear or disappear when you click `Cycle SDRAM` a few times in Developer options?

**Comment by MFreudenthaler** [comment]
I still have solved the Problem. Something was wrong with the external clock gen and with my cable management. After resoldering and use new wires it still works perfect
