### ISSUE TITLE
No sharpness

### ISSUE THREAD

**Issue by andreacampanella** [ramapcsx2/gbs-control#5]
Would be great to have the sharpness line in the original firmware.

**Comment by ramapcsx2** [comment]
Well, maybe.
I'm not sure this is a good option to have, as no matter the setting, it reduces image quality.
The original firmware does this by adjusting the 2D peaking variables. 
They are very complex, spread about 15 or so registers, so their full effect is hard to qualify.
So far one thing held true though: Turning of 2D peaking always improved quality.

Maybe one day we'll find good sets of parameters for this but until then, I'd rather focus on other things first.

**Comment by ramapcsx2** [comment]
Closing this but the request is of course not forgotten.
