### ISSUE TITLE
Can on board processor be removed?

### ISSUE THREAD

**Issue by luisfcorreia** [ramapcsx2/gbs-control#500]
I'm wondering if old controller could be removed, as we are already controllong the board

Curiosity, that's all :)

**Comment by ramapcsx2** [comment]
Yep, in theory and a small praxis test that I did once.. it's fine :p

**Comment by luisfcorreia** [comment]
additionally, I guess that the 24C12 EEPROM is also unused, or it is?

**Comment by ramapcsx2** [comment]
I forgot, there's an EEPROM? So yea, if this is for data for the original MCU, off it goes! :p

**Comment by luisfcorreia** [comment]
it's a small I2C connected soic chip

it will also go :)

**Comment by luisfcorreia** [comment]
Apparently, you can remove all these components, depending on your usecase

enjoy hacking!

thanks for such a nice ork on a crucial project
![1000003238-01](https://github.com/ramapcsx2/gbs-control/assets/191885/9d2db5e7-41b2-4d97-bc70-b5bdee72ce3b)

**Comment by luisfcorreia** [comment]
@ramapcsx2 Feel free to add this picture to the wiki
