### ISSUE TITLE
RGB-HV output

### ISSUE THREAD

**Issue by oziphantom** [ramapcsx2/gbs-control#502]
Is it possible to get RGBHV output and not RGBs output? 

Basically I'm looking to get VGA -> RGBHV which it seems nothing does.

**Comment by Nuck-TH** [comment]
VGA is RGBHV by definition. Or you mean VGA 15khz?

**Comment by ramapcsx2** [comment]
The default output is RGBHV already?

**Comment by oziphantom** [comment]
Say the 640x480 at 60hz or possibly SVGA spec of 800x600 at 60hz transmitted via a DE-15 connector to analouge RGB 576i 0.7 p-p with a 15khz Horizontal rate at 50hz vertical or 480i at 60hz vertical suitable for a DB9 pin RGB with a H and V sync output.

**Comment by ramapcsx2** [comment]
I guess you mean you want to use the bypass function, but with H+V syncs. That's something the chip can't do, or I haven't found out how to do it.

**Comment by Nuck-TH** [comment]
Also this chip can't do framerate conversion.

**Comment by oziphantom** [comment]
seems "GBS-Control" and this "GBSC"  https://www.ebay.com.au/itm/314802317450 are not the same thing, hence my confusion. 
Thanks for your help.

**Comment by ramapcsx2** [comment]
Well, just as info: This *is the same*, though they added a bunch of hardware to make it more convenient.
It still runs this software without any modifications (as far as I know) :)
