### ISSUE TITLE
Please make the project compatible with Platformio

### ISSUE THREAD

**Issue by Metaln00b** [ramapcsx2/gbs-control#504]
Unfortunately, it is very difficult to build the project easily.

It not only helps you to develop, but also helps the community to help you to develop.
There are no version numbers of the used libraries mentioned. This always ends in compiler warnings :D

Is there any way I can help you make the project compatible with Platformio?
Is there possibly already a fork for it?

Thanks in advance

**Comment by ramapcsx2** [comment]
Hey,
there is some work towards porting the project to a different chip (ESP32 variant), which also comes with a new view on platform.
I support the move away from Arduino to the vanilla IDF, and that would also affect other generalization platforms such as yours.
