### ISSUE TITLE
Can I use this cfw with the hdmi based model?

### ISSUE THREAD

**Issue by fadedrobin** [ramapcsx2/gbs-control#51]
I was wondering if I could use this mod on the HDMI version to achieve a setup similar to a OSSC? Has anyone tried this? How does it look? What sort of interference is there? The product I'm talking about is <a href="https://www.ebay.com/itm/Arcade-Game-RGB-CGA-EGA-to-HDMI-HD-Game-Video-Converter-Output-Board/263475234308?_trkparms=aid%3D555017%26algo%3DPL.CASSINI%26ao%3D1%26asc%3D54339%26meid%3D6365abcfbc1148d3840f9847e436e7fd%26pid%3D101006%26rk%3D1%26rkt%3D1%26%26itm%3D263475234308&_trksid=p2045573.c101006.m3226">this</a>

**Comment by ramapcsx2** [comment]
Yes, these boards work well :)

The HDMI limits some of the special modes. I couldn't get pass-thtough from 240p consoles working, while my TFT does accept it over VGA (as 720x240).
Other than that, the regular presets all work and look good.

**Comment by fadedrobin** [comment]
Thank you for the information. I am excited to try this out on my VGA CRT and my HD LCD soon. Does it work with multiple set up on the same network?

**Comment by ramapcsx2** [comment]
You mean on the WiFi network? Yeah, although each will identify as "gbscontrol", each will get a unique IP.

**Comment by fadedrobin** [comment]
Is there a way to change what it's name is? Like for example I want something like gbs-bedroom or gbs-vga instead of the regular gbscontrol?

**Comment by ramapcsx2** [comment]
Sure, find the "gbscontrol" strings throughout the source and change them to what you want them to be.

**Comment by fadedrobin** [comment]
Thank you for answering my questions. I'll definitely try this out soon.
