### ISSUE TITLE
Active frametime lock causing intermittent video dropout (black screen), on both options

### ISSUE THREAD

**Issue by Pajamaland** [ramapcsx2/gbs-control#535]
Using both option 0 and option 1 for active frametime lock, neither works. I experience frequent video dropouts, where the screen will go black for a few seconds before coming back on. The sad thing is the vsync issues totally disappear when it **is** working. I'm using the McBazel ODV-GBS-C prebuilt, with a PAL Wii running through component.

**Comment by ramapcsx2** [comment]
It's highly TV / scaler / receiving device dependent whether the options work or work nicely.
A clock gen might help, as it opens another way to do it.

**Comment by Pajamaland** [comment]
Yeah, I figured. Ordered a different prebuilt with an external clock gen.
