### ISSUE TITLE
WIFI settings not saved

### ISSUE THREAD

**Issue by fkooistra** [ramapcsx2/gbs-control#538]
Hi, I upgraded to the new build using Arduino studio without any errors. Although everything seems to be functioning as expected, when I select a home network with its (correct) password the settings are not saved after reboot and the device starts in AP-mode again. Could this be build related?

**Comment by Metaln00b** [comment]
Try using 2.4GHz WiFi

**Comment by diegoapn** [comment]
firmware problem, i compiled today and didn´t work, i used other firmware and worked at first time.

**Comment by Metaln00b** [comment]
Would one of you be so kind and look into the serial console to see if an error message or something similar appears after setting the credentials and post it here? 

Maybe something will appear there.

At the same time, it would also be great if you could find the relevant line of code and analyze it if necessary, that would help.

Thanks a lot

**Comment by YoImLee** [comment]
Verify your flash size settings in the Arduino IDE and make sure you are running esp8266 version 2.6.3, not 3.0 or newer.

**Comment by fkooistra** [comment]
I downgraded the esp8266 boards package back to 2.6.3, and used the following library versions:
- ESP Async Webserver: 1.2.3
- ESP8266 and ESP32 OLED Driver for SSD1306: 4.4.1
- ESP8266-ping: 2.0.1
Basically, following the software setup instructions and ignoring library updates suggested by the Arduino IDE. This seems to work and my GBSp-control connects to my Wifi-network.

**Comment by fkooistra** [comment]
Issue fixed by using exact package and library versions as provided with setup instructions.
