### ISSUE TITLE
How do I flash new firmware onto the GBS-C using Windows 11

### ISSUE THREAD

**Issue by Route66Fan** [ramapcsx2/gbs-control#544]
The GBS-C that I have is the one by Mr. Ao. 
I would like to do this, but I can't easily access the micro USB port on the WiFi expansion board due to it being located behind some RCA\Component jacks.

**Comment by YoImLee** [comment]
If your computer and GBS are on the same network, you can try the "enable OTA" option on the GBS. It should pop up as a device in your Arduino IDE just like it would when it's connected through USB. If it doesn't work you may have to set your firewall network profile to "private" in your Windows settings, or whitelist the Arduino IDE in there somewhere. That might help.

**Comment by Route66Fan** [comment]
> If your computer and GBS are on the same network, you can try the "enable OTA" option on the GBS. It should pop up as a device in your Arduino IDE just like it would when it's connected through USB. If it doesn't work you may have to set your firewall network profile to "private" in your Windows settings, or whitelist the Arduino IDE in there somewhere. That might help.

That worked, thank you!

**Comment by popperclopper** [comment]
Hi. Were you able to reflash GBS? Does sync work?
Do RCA and S-video work?
What firmware did you install?
