### ISSUE TITLE
Video Tearing/Artifacts

### ISSUE THREAD

**Issue by diggles4** [ramapcsx2/gbs-control#555]
I just completed this build per Voultar's guide and installed the optional Si5351. I am using a VGA to HDMI adapter, similar to his in the video.

Web GUI works great, but I have not been able to get an image on any display. Most displays give "no signal" but I was able to capture an intermittent image on a single display (iPad via Orion): https://i.imgur.com/0IQFPrH.png

This is the output I get with 480p. With 1280x960 I can get more visual artifacts, while the other modes produce no image at all. Pass Through makes only audio come through.

Looking for advice one where to start diagnosing. Thank you!

(EDIT: using component video via PS2 with this cable: https://www.amazon.com/dp/B07VCT41QV)

**Comment by ramapcsx2** [comment]
Hey, there is some kind of big problem, either in the input path, or the Si5351 enabled output path.
To check out whether it is the Si, you can just disconnect one of the cables to it, either SCL or SDA are fine.
This makes the software think that there's no clockgen installed, and use the normal mode.

**Comment by diggles4** [comment]
Sure enough, disconnecting SDA cleaned up the signal. I have tried resoldering each of the connections on Si5351 but still have the same issue. Is it possible that the Si5351 is dead?

EDIT: 
I've tried pulling Si5351 power from C41 and C42. Ground from C41
PSU: https://www.amazon.com/dp/B09W96X88K

**Comment by ramapcsx2** [comment]
Bad Si5351 is a possibility, but it could also be a bad connection of the clock output (into the ASIC), or any other such issue.

**Comment by diggles4** [comment]
Thank you for the help, rama, much appreciated! I will order another Si5351, as my joints are all show conductivity to ship pins without bridging.

As for the PSU... any chance that's the culprit? The reason I ask is because I have to plug it in a specific sequence for it to power the board and ESP. Seems if I plug into outlet before barrel, it almost never powers both boards. Barrel before outlet, leads to higher success rate. If sequenced properly, all LEDs act appropriately.

**Comment by ramapcsx2** [comment]
Well, that is also weird :p
I can't really debug your board from here, but if something seems fishy, go investigate! :)

**Comment by diggles4** [comment]
Well, as an update, I've now tried the following and still have this issue.
-Re-soldering ESP and Si5351
-Tried a second Si5351
-Reflashed ESP just because

One of the only things I've been reluctant to go back and check are the add-on capacitors... I assume this couldn't possibly be the issue though?

Also, I figured out the PSU thing. If I have the VGA->HDMI adapter powered by the 5v spot near the jack, I have inconsistencies with ESP booting properly when plugging in. If I don't have the adapter powered by the board, or plug it in second, I have no issues.

**Comment by ramapcsx2** [comment]
There's an HDMI dongle? This might be the cause for the clockgen sync issue. Some of those don't like slightly off spec clocks.
If you can, try to use the VGA out directly, if only to confirm that it works then > HDMI dongle is bad.

**Comment by YoImLee** [comment]
Did you check the description in Voultar's video? If you followed along exactly with the video there's a chance you soldered the 100 Ohm resistor for the RGB sync input incorrectly, connecting it to the RGB blue input. I'm not sure if this would affect the component input but it's worth checking anyway.

**Comment by diggles4** [comment]
I can confirm it does not work with VGA only either, just stays as a black screen with the monitor detecting an input but not able to connect. 

For what it's worth, I've still only been able to get a "picture" from the Orion app on iPad, which is a bit bizarre. Other TVs/monitors just stay blank or claim "incompatible format".

I also tried a different PSU (WSU050-4000 by Triad). Same results all around.

Could these 10 micro farad capacitors could have any effect? I'm hesitant to mess with them. These are the types I installed and they _seem_ to be fine: https://www.digikey.com/en/products/detail/samsung-electro-mechanics/CL21A106KPCLQNC/3888060

I have not checked the 100ohm resistor, as I understand that only effects the VGA (or RGB) input.

Thanks again for the assistance, everyone :)

**Comment by ramapcsx2** [comment]
Hey, I think we've exhausted the easy things to suggest :p 
Something isn't right when your clock gen should provide the clock to the output section, but it works when the ASIC does it itself.
What that something is.. unless you oscope some signals, it's hard to know.

**Comment by diggles4** [comment]
Well, the plot thickens! I figured I'd pick up another ESP and GBS for the heck of it (since I already had two PSUs and Si5351). I have now assembled both and have the same issue on both!

Is it possible that the capacitors I used for C23, C41, C42, and C48 (linked above) are incorrect? Should I have not removed C11 on a GBS8200 board (black buttons)? Does any of the prep work I've done for future SCART (removing pots and adding 100 ohm resistor) have anything to do with the component input issues I've had?

**Comment by YoImLee** [comment]
Can you show us some pictures?

**Comment by diggles4** [comment]
![IMG_2559](https://github.com/ramapcsx2/gbs-control/assets/3486893/03b036b1-93a6-412f-b861-d8b86907e20c)
![IMG_2560](https://github.com/ramapcsx2/gbs-control/assets/3486893/91262cce-6faf-4805-8ddf-4de6becb79df)

Please ignore my terrible soldering job... I promise I'm getting better. 

EDIT: the jumper is bridged underneath, forgot to mention!

**Comment by YoImLee** [comment]
Looks okay to me, what about the resistor on the back?

**Comment by diggles4** [comment]
Does this resistor have anything to do with component input though?

![2020_0610_133240_001](https://github.com/ramapcsx2/gbs-control/assets/3486893/85b12c3e-e2f3-44c4-a3eb-34a6237095ea)

**Comment by YoImLee** [comment]
I'd say there's a chance it could mess things up, try removing it and see if the component input starts working. If it does and you want to still be able to plug in RGBs sources down the line mount the resistor like this instead (image from Voultar's video description):

![k2bf42k](https://github.com/ramapcsx2/gbs-control/assets/77938792/a95fbac4-d3c5-40c2-bd78-54cbd9a4018d)

**Comment by diggles4** [comment]
Wow, thank you for pointing that out! I completely missed that comment on his video.

I have now fixed that resistor - no improvement to component.

**Comment by YoImLee** [comment]
You could try enabling developer mode in the web UI and taking a look at the log when turning on the PS2.

**Comment by diggles4** [comment]
I enabled developer mode. **Here is what I get when turning on system**:
Scanning inputs for sources ...
Activity detected, input: Component

2345678
Format change: 1 <stable>
ADC offset: R:42 G:42 B:44
clock gen reset: 81000000
HTotal Adjust: -5
Active FrameTime Lock enabled, adjusting external clock gen frequency

preset applied: 720x480 for NTSC 60Hz 



**Also, when turning off and back on I get this**:
 (debug) ign. length: 0x4E
 (debug) ign. length: 0x63



**Here is what I get when switching to 1080p output (no image)**:
source Hz: 59.93802 new out: 66.53770 clock: 79402704 (-28597296)
ABHT: large diff
retry
ABHT: large diff
retry
ABHT: large diff
retry
ABHT: large diff
retry
ABHT: large diff
retry
ABHT: large diff
retry
ABHT: large diff
retry
ABHT: large diff
give up



**Here is what I get when switching to 480p (distorted image - see original pic)**:
sync skipped ofr wrong: 88.49
ABHT: large diff
retry
ABHT: large diff
retry
ABHT: large diff
retry
ABHT: large diff
retry
ABHT: large diff
retry
ABHT: large diff
retry
ABHT: large diff
retry
ABHT: large diff
give up


For the sake of being completely thorough, this is my BOM:

ESP: https://www.amazon.com/dp/B010O1G1ES
Si5351: https://www.amazon.com/dp/B07X7ZT7KJ
GBS: https://www.amazon.com/dp/B01IBJCAIG
PSU: https://www.digikey.com/en/products/detail/triad-magnetics/WSU050-4000/3094945
PSU2: https://www.amazon.com/dp/B09W96X88K
Capacitors: https://www.digikey.com/en/products/detail/samsung-electro-mechanics/CL21A106KPCLQNC/3888060
Resistor: https://www.digikey.com/en/products/detail/panasonic-electronic-components/ERJ-3EKF1000V/196074

And as for what I did...

1. Flashed GBS software to ESP
2. Removed RGB potentiometers and replaced with bridge
3. Added resistor (pic above)
4. Removed C11 from GBS
5. Added capacitors, stacked on top of C23, C41, C42, and C48
6. Bridged GBS (jumper) to disable the GBS original controller
7. Attached all wires, ESP, and Si5351 as shown above

**Comment by YoImLee** [comment]
Does the gbs start working if you toggle the "Disable External Clock Generator" option and reboot the gbs? If it does then you might have gotten some bad clock generator boards. I know there have been some bad batches of those in the past and they might still be floating around in some places.

Looking at the latest reviews from the Amazon listing you linked it might very well be the case. I'm seeing a lot of 1 star reviews with people saying they don't work.

Also, with the clock generator disabled you may have to turn off FrameTime Lock or you might get intermittent dropouts on your display.

**Comment by diggles4** [comment]
Yes, the GBS Control appears to work just fine with the External Clock Generator disabled. Similar results when disconnecting the SCL or SDA wire from the Si5351.

Hmm, I guess I should just try a third Si5351 and see... purchasing from a different seller this time. Stay tuned! Thanks again for the help :)

**Comment by diggles4** [comment]
Well, the new Si5351s came in (different seller this time: https://www.amazon.com/dp/B09DM96KGS) and they BOTH work perfectly.

Long story short, don't buy these: https://www.amazon.com/dp/B07X7ZT7KJ

Thank you, rama and YolmLee. I appreciate you!!!
