### ISSUE TITLE
Sacing slots no working on new update

### ISSUE THREAD

**Issue by tvirusx** [ramapcsx2/gbs-control#56]
Hi there...
Just did an update and try to save the settings but when I do select the slot it gives me: 

saveUserPrefs: open file failure

and if I try to save it says that I need to select a slot first.

thanks once again

Thompson

**Comment by ramapcsx2** [comment]
Did you update your Arduino environment lately?
Check the build options and make sure that "Flash Size: 4M (1M SPIFFS)" is selected.

Somehow the defaults changed to having SPIFFS disabled.
If that's intended, I need to add some more checks..

**Comment by ramapcsx2** [comment]
I've added a screenshot for this to the Wiki :)
https://github.com/ramapcsx2/gbs-control/wiki/Software-Setup#esp8266-ide-settings

**Comment by tvirusx** [comment]
Yep... that did the trick.... thanks very very much u guys awesome...😆😀
