### ISSUE TITLE
Questio on CAP, HELP

### ISSUE THREAD

**Issue by tvirusx** [ramapcsx2/gbs-control#57]
This is a question about a CAP. For some reason am missing a cap here on C14 on the picture. This cap if between the controller and the buttons. I have another board here but I do not have a multi tester that measures CAPs to find out the value to install a new on the missing space. Can some with the proper tester help me on discovering the value of this cap??? I looked all over the place for the scheme of the board but I could not find it.
![image](https://user-images.githubusercontent.com/13492126/50923999-4d4c5a00-141c-11e9-8d54-1e6a0bd16719.png)

I know this has nothing to do with this project but this is the best place I found to ask. Or indicate a proper multimeter that I could use to test this, cause the smart tweezers that I found that could test this in $149 and up.

Thanks very much for ur help.

Thanks

T

**Comment by ramapcsx2** [comment]
C14 is a power supply bypass capacitor for the small EEPROM chip. It doesn't connect to the buttons or have any other important role.
It's fine if yours is missing.
If you need to replace it, it will be 100nF.
