### ISSUE TITLE
Overlay or Bezel options

### ISSUE THREAD

**Issue by lcsjunior** [ramapcsx2/gbs-control#71]
Do you think it would be possible to have Overlay or Bezel options for gbs-control?

**Comment by ramapcsx2** [comment]
Hm, no, I don't think it's possible to do what you have in mind.
Any kind of overlay would have to be inserted digitally, and there's just the OSD generator that can do this.
The OSD can't do any tricks from what I've seen, especially nothing that could be used for full screen effects.
