### ISSUE TITLE
Can this chip support mirroring?

### ISSUE THREAD

**Issue by DavidShoe** [ramapcsx2/gbs-control#76]
Want to use this on a Starblade but the game uses a mirror to display to the user.  My LCD has a diagnostic mode Mirror but it is the wrong axis.  Any chance there is something in this units chipset that might help?

**Comment by ramapcsx2** [comment]
No, I don't think so. I haven't seen a mirroring effect in all the time working with this chip.

**Comment by ramapcsx2** [comment]
Sorry, can't do it.
