### ISSUE TITLE
Noise in ps2\dreamcast games and shaky sega saturn PAL picture

### ISSUE THREAD

**Issue by Iraito** [ramapcsx2/gbs-control#82]
![IMG_20191006_084610](https://user-images.githubusercontent.com/3323267/66265586-62261480-e819-11e9-923d-dc0528de6ad5.jpg)

![1](https://user-images.githubusercontent.com/3323267/66264021-df439080-e7fd-11e9-8ea4-73352e314f21.jpg)

The noise is barely visible while playing but it's there, sometimes it gets more pronounced while playing on ps2, everything through scart and sync stripper with a 12v switching power supply.

The ps1 is crystal clear on the other hand, pretty much the same level of quality seen on emulators and this while using the same scart cable used for ps2.

I also have a problem with the sega saturn, the signal has the same quality it has on ps1 but the picture shakes continuously, i also noticed that the blue light of the arduino lights on and off repeatedly, only with the saturn.

**Comment by ramapcsx2** [comment]
Solved on the forums.
