### ISSUE TITLE
layout of the pins on the mtv 230

### ISSUE THREAD

**Issue by sethenstien** [ramapcsx2/gbs-control#84]
tried looking everywhere for one and there isn't a layout of the pins on the mtv 230 anywhere, just where the debug pin is. any help?

**Comment by tomudo** [comment]
http://www.keil.com/dd/docs/datashts/myson/mtv230m.pdf
2nd pin from lower-left

**Comment by ramapcsx2** [comment]
Yes, you must not bridge these pins.
It helps to wetten the pin and your wire first, then laying the wire flat against the pin, before connecting the 2 with just a touch of the iron.
