### ISSUE TITLE
Not all browsers support css property min-width: max-content

### ISSUE THREAD

**Issue by Nuck-TH** [ramapcsx2/gbs-control#85]
There is number of browsers that doesn't support css property min-width: max-content:
* chrOpera (Opera >15)
* Firefox <66
* Browsers based on UXP (Pale Moon, Basilisk, Iceweasel UXP)

Without it buttons get jumpy: https://sta.sh/0tf5335e05

Actually they support it with vendor prefixes:
* -moz-max-content for Firefox and UXP
* -webkit-max-content for chrOpera

So you need to add:
`min-width: -moz-max-content;`
`min-width: -webkit-max-content;`
to btn-h and button classes

**Comment by ramapcsx2** [comment]
Thanks for letting me know, fix is out:
https://github.com/ramapcsx2/gbs-control/commit/3aea7471266fb1ad7ce18a9cdd16e8eb9519b884
