### ISSUE TITLE
RGB Bypass сustom preset save error.

### ISSUE THREAD

**Issue by RomanF2B** [ramapcsx2/gbs-control#92]
How to save custom preset PC DOS Mode 720x400@70hz - > 1280x720 .All VGA modes when saving a custom preset give an error.

input 720x400@70hz -> output 1280x720@70hz
<reset>
Activity detected, input: RGB
VSync: present
HSync: present
RGB/HV bypass 
ADC offset: R:44 G:45 B:43
post preset done (preset id: 3) for RGB Bypass (HV Sync)
HTotal Adjust: -353, source Hz: 70.112, output Hz: 70.159
saving to preset slot 1
open save file failed!

input 640x480@60hz -> output 1280x720@60hz
<reset>
Activity detected, input: RGB
VSync: present
HSync: present
RGB/HV bypass 
ADC offset: R:44 G:45 B:43
post preset done (preset id: 3) for RGB Bypass (HV Sync)
HTotal Adjust: -14, source Hz: 60.162, output Hz: 60.204
saving to preset slot 1
open save file failed!

**Comment by ramapcsx2** [comment]
Yep, you can't save bypass mode adjustments with the current system.
There are several problems to overcome if I were to add support for this, and it's not a priority at this time.

I may get to it some day though.
