### ISSUE TITLE
OTA Updates

### ISSUE THREAD

**Issue by TioChico27** [ramapcsx2/gbs-control#93]
Hello!

Are OTA updates already working? How does it work?

Amazing project by the way.

Regards.

**Comment by Nuck-TH** [comment]
Press enable ota in web interface and choose gbs adress in Tools - Board in Arduino. Then you can upload the sketch. However, even while there is Restart option in web interface, i recommend to power cycle the board.
That's it.

**Comment by TioChico27** [comment]
> Press enable ota in web interface and choose gbs adress in Tools - Board in Arduino. Then you can upload the sketch. However, even while there is Restart option in web interface, i recommend to power cycle the board.
> That's it.

Thanks for reply.

It's working now!

Regards.
