### ISSUE TITLE
Can GBS-Contol handle 15KHz, 24KHz and 31KHz?

### ISSUE THREAD

**Issue by hlide** [ramapcsx2/gbs-control#95]
Not an issue per se. All is said in the title. I have a GBS8220 and a SHARP X68000 XVI Compact. The chance to get a working 15KHz/24KHz/31KHz CRT are pretty low.

**Comment by ramapcsx2** [comment]
Yes it can.
Support for 24kHz isn't great yet. You probably have to reposition the image and restart the scaler.
The other formats are well supported.
